_portal_errors:
    resource: "@SuluWebsiteBundle/Resources/config/routing_error.yml"
    type: portal
_errors:
    resource: '@FrameworkBundle/Resources/config/routing/errors.xml'
    prefix:   /_error
